apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservicio-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservicio-java
  template:
    metadata:
      labels:
        app: microservicio-java
    spec:
      containers:
      - name: container-microservicio-java
        image: cristianaliaga/repo-image:latest
        ports:
        - containerPort: 8080